<a href="https://colab.research.google.com/github/rajat1911996sharma/Machine-Learning-Model-Life-Cycle/blob/Regresion-Models/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ANN with Stochstic Gradient Descent

```
Step 1: Randomly initialize the weights to small numbers close to 0 (but not 0).

Step 2: Input the first observation of your dataset in the input layer, each feature in one input node.

Step 3: Forward-Propagation: from left to right, the neurons are activated in a way that the impact of each neuron's is limited by the weights. Propagate the activations until getting the predicted result y.

Step 4: Compare the predicted result to the actual result. Measure the generated error.

Step 5: Back-Propagation: from right to left, the error is back-propagated. Update the weights according to how much they are responsible for the error. The learning rate decides by how much we update the weights.

Step 6: Repeat Steps 1 to 5 and update weights after each observation (Reinforcement Learning). Or: Repeat Steps 1 to 5 but update the weights only after a batch of observations (Batch Learning).

Step 7: When the whole training set passed through the ANN, that makes an epoch. Redo more epochs.
```

##Business Problem

Customers are leaving a large bank. We are dealing with values only in Europe for now. So, we get 10,000 customers. We are to find which customers are at highest risk of leaving the bank.

Should the person get a loan or not should the person get credit or not ?

Maybe which transcations are Fradualent.





##Data Preprocessing

###Importing the Libraries

In [200]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


###Importing the dataset


In [201]:
df = pd.read_csv('Churn_Modelling.csv')


In [202]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

RowNumber, CustomerId, Surname seems to have no bearing on the final outcome.

So, we will exclude those.

In [203]:
X = df.iloc[:, 3:-1].values #taking the values from 3rd column
y = df.iloc[:, -1].values


###Encoding the categorical variable

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


Geography and Gender are categorical varibles that are potentially useful for the final outcome.

####Label Encoding of "Gender" Column

In [205]:
X[:, 2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [206]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [207]:
X[:, 2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [208]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [209]:
X.shape

(10000, 10)

In [210]:
#X = np.asarray(X).astype('float32')

In [211]:
X.shape

(10000, 10)

In [212]:
y.shape

(10000,)

In [213]:
#y = np.asarray(y).astype('float32')
#y.shape
#type(y)

####One Hot Encoding of "Geography" Column

In [214]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder= 'passthrough')
X = ct.fit_transform(X)
type(X)


numpy.ndarray

In [215]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))
type(X)


numpy.ndarray

In [216]:
X = np.asarray(X).astype('float32')

In [217]:
X

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085578e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888523e+04],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190781e+04]], dtype=float32)

###Split the dataset into Test Set and Training Set

In [218]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

###Feature Scaling(Absolutely Complusory for Deep Learning)

In [219]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [220]:
X_train.shape

(8000, 13)

In [221]:
X_test.shape

(2000, 13)

In [222]:
y_train.shape

(8000,)

In [223]:
y_test.shape

(2000,)

In [224]:
'''y_train = y_train.reshape(-1,1)
y_train.shape'''
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)

In [225]:
'''y_test = y_test.reshape(-1,1)
y_test.shape'''
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

##Building an ANN

###Initializing the ANN

In [226]:
from tensorflow.keras.models import Sequential
ann = Sequential()

###Adding the input layer and the first hidden layer 

In [227]:
from tensorflow.keras.layers import Dense
ann.add(Dense(units=15,activation='relu'))

How do we know how many neurons we want ?

There is no rule of thumb. It is based up on intuition.

Depends on the hyperparameters (parameters that wont be trained inside this model)



###Adding the second hidden layer

In [228]:
ann.add(Dense(units=15,activation='relu'))

###Adding the output layer

In [229]:
ann.add(Dense(units=1, activation='sigmoid'))
#sigmoid for the probablity of a binary variable
#for non binary(categorical variable), softmax should be used

##Training the ANN

###Compliling the ANN

In [230]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#adam perform Stochastic Gradient Descent
#for binary classification, we use bianry_crossentropy
#for non binary classification, we use categorical_crossentropy
# we need to enter the metrics as a list, we chose accuracy

###Training the ANN on the Training Set

In [231]:
ann.fit(X_train, y_train , batch_size=32, epochs=100)
#batch size is the number of results you want to be compared to 
# to get the results at the same time

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.7350 - accuracy: 0.5275
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4560 - accuracy: 0.8027
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4095 - accuracy: 0.8227
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3953 - accuracy: 0.8332
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3771 - accuracy: 0.8468
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3625 - accuracy: 0.8494
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3448 - accuracy: 0.8599
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3452 - accuracy: 0.8557
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3437 - accuracy: 0.8557
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3431 - accura

##Making the predictions and evaluating the model

###Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [237]:
print(ann.predict(scaler.transform([[1,0,1,600,0,40,3,60000,2,1,1,50000]])))

ValueError: ignored

I tackled this problem with adding an additional 0 parameter at the end

In [238]:
print(ann.predict(scaler.transform([[1,0,1,600,0,40,3,60000,2,1,1,50000,0]])))

[[0.]]


In [239]:
#Are the chances of employee greater than 50$ ?
print(ann.predict(scaler.transform([[1,0,1,600,0,40,3,60000,2,1,1,50000,0]])) > 0.5)


[[False]]


So, the customer might not leave the company

In [240]:
print(ann.predict(scaler.transform([[1,0,1,600,0,40,3,60000,2,1,1,50000,0]])) == 0.03827231)


[[False]]


###Predicting the Test Set results

In [241]:
ann.predict(X_test)

array([[0.26041943],
       [0.18873262],
       [0.07494977],
       ...,
       [0.380043  ],
       [0.16065687],
       [0.23386467]], dtype=float32)

In [247]:
pred = (ann.predict(X_test) > 0.5)

###Evaluating the predictions

In [242]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [248]:
print(classification_report(y_test,pred))
print('\n')
print(confusion_matrix(y_test,pred))
print('\n')
print(accuracy_score(y_test,pred))
print('\n')

              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1595
           1       0.72      0.49      0.58       405

    accuracy                           0.86      2000
   macro avg       0.80      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000



[[1517   78]
 [ 207  198]]


0.8575




[Additional content on CNN](https://www.superdatascience.com/blogs/the-ultimate-guide-to-artificial-neural-networks-ann)