<a href="https://colab.research.google.com/github/rajat1911996sharma/Machine-Learning-Model-Life-Cycle/blob/Regresion-Models/Artificial_Neural_Network(Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dataset from Combined Cycle Power Plant Dataset

[The infomation about the dataset](https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant)

#Artificial Neural Network Regression

###Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##Data Preprocessing

###Importing the Dataset

In [2]:
df = pd.read_excel('Folds5x2_pp.xlsx')

In [3]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [7]:
X.shape

(9568, 4)

In [8]:
type(X)

numpy.ndarray

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [9]:
y.shape

(9568,)

In [10]:
type(X)

numpy.ndarray

###Splitting the Dataset into Training Set and Test Set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

##Building the ANN

###Initializing the ANN

In [12]:
from tensorflow.keras.models import Sequential
ann = Sequential()

###Adding the first layer and the hidden layer

In [13]:
from tensorflow.keras.layers import Dense
ann.add(Dense(units = 4, activation='relu'))

###Adding the second hidden layer

In [14]:
ann.add(Dense(units = 4, activation='relu'))

###Adding the output layer

In [15]:
ann.add(Dense(units=1))
#As we are doing univariate regression function, so we choose no activation function
#binary Categorical variable is sigmoid
#multivariate categorical variable is softmax


##Training the ANN

###Compiling the ANN

In [16]:
ann.compile(optimizer='adam', loss='mean_squared_error')
#mse for regression models

###Training the ANN model on the Training Set

In [17]:
ann.fit(X_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 879us/step - loss: 247365.5029
Epoch 2/100
240/240 [==============================] - 0s 905us/step - loss: 210627.2258
Epoch 3/100
240/240 [==============================] - 0s 952us/step - loss: 205036.5375
Epoch 4/100
240/240 [==============================] - 0s 898us/step - loss: 159188.8520
Epoch 5/100
240/240 [==============================] - 0s 920us/step - loss: 1582.0452
Epoch 6/100
240/240 [==============================] - 0s 925us/step - loss: 322.2261
Epoch 7/100
240/240 [==============================] - 0s 934us/step - loss: 320.1269
Epoch 8/100
240/240 [==============================] - 0s 908us/step - loss: 317.1462
Epoch 9/100
240/240 [==============================] - 0s 880us/step - loss: 307.4277
Epoch 10/100
240/240 [==============================] - 0s 870us/step - loss: 306.4349
Epoch 11/100
240/240 [==============================] - 0s 895us/step - loss: 296.5164
Epoch 12/100
240/240 [=================

##Predicting the test set results

In [18]:
ann.predict(X_test)

array([[432.10297],
       [463.65903],
       [467.38116],
       ...,
       [474.24384],
       [441.6279 ],
       [460.61966]], dtype=float32)

In [19]:
pred = ann.predict(X_test)

##Evaluating the Test Set results

In [20]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,auc,roc_curve

In [23]:
print(mean_squared_error(y_test,pred))
print('\n')
print(mean_absolute_error(y_test,pred))
print('\n')
print(r2_score(y_test,pred))
print('\n')


26.014346159935922


4.099287897028271


0.9110583655034566


