<a href="https://colab.research.google.com/github/rajat1911996sharma/Machine-Learning-Model-Life-Cycle/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

50 Start ups companies and what waas their profit.
Profit is their dependent variable
other are independent

which of the independent yield best profits

#Muliple Linear Regression

##Data Preprocessing

#Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

##Importing the Dataset

In [2]:
df = pd.read_csv('50_Startups.csv')

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [12]:
X = df.drop('Profit',axis=1).values
y = df['Profit'].values

KEY NOTE:

We dont need to use all of our dummy variables because it will result in dummy variable trap. because if there are 2 dummy vaiables d1 and d2 then d1 = 1-d2 but in a regression eqn.

y = b0 + b1x1 +b2x2 + b3x3 + b4d1 +b5d2

these will disturb each others value and worsen the o/p

What is p-value?

lets take a coin toss
there are 2 hypothesis:

H0: This is a fair coin

H1: This is not a fair coin

we will start by assuming H0 is true, 
the coin toss prob. for tails for successive toss

Tails                    P-Values

0.5                     

0.25

0.125

0.0625

                   alpha=0.05
                   when we see tails for theshold of this alpha, we decide that our H0 is false

0.03125

0.015625

we get an uneasy feeling that alpha has been broken

Building a model:
5 methods of building a model

1. All-in
(we throw in all the variables in the model)
2. Backward Elimination
(a. select a significance level to stay in the model

b. fit the ful model (all in approach)

c. Consider the predictor with highest p-value

d. Remove that predictor)

e. Fit the model w/o this variable.
keep doing this until highest p-value is less than significance level.
)
3. Forward Selection 
(
  a. select a significance level 

  b. Fit all simple regresion models and Select the one with lowest p-value.

  c.Keep this variable and fit all possible models with one extra predictor added to the one(s) I already have.

  d.Consider the predictor with lowest p-value. if p-value < significance level then go to c. otherwise end
)
Keep the previous model before ending
4. Bidirectional elimination
(
  a. Select a SL

  b. Perfrom the next step of forward selection

  c. perform all the steps of backward eliminatiom 

  d. until no new variables can enter and no old variables can exit.
)
5. Score Comparision
(
  a. Select a criterion of goodnes of a fit(like r2)

  b. construct all possible regression models: 2^n -1 total combinations.

  c.Select the one with best criterion.
  
  end
)



#Encoding Categorical variables

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' ,OneHotEncoder(),[3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [9]:
X

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

#Splitting the Dataset into the training set and test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#Training the Multiple Linear Regresssion model on Training Set

In [11]:
'''Do we have to do something to avoid dummy variable trap?
The answer is No

We dont need any class to use model building methods because the library will do it for us
'''

'Do we have to do something to avoid dummy variable trap?\nThe answer is No\n\nWe dont need any class to use model building methods because the library will do it for us\n'

In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#Predicting the Test set Results

In [18]:
pred = lr.predict(X_test)

In [19]:
pred

array([103015.20159795, 132582.27760816, 132447.73845175,  71976.09851258,
       178537.48221057, 116161.24230167,  67851.69209676,  98791.73374687,
       113969.43533014, 167921.06569552])

In [20]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [21]:
pred - y_test

array([  -267.17840205, -11677.12239184, -13674.21154825,  -5822.73148742,
       -12512.90778943,  11152.93230167, -13377.36790324,   1308.17374687,
         3617.18533014,   1733.12569552])

In [24]:
np.set_printoptions(precision=2)
#number of digits in floating point with presicion
np.concatenate((pred.reshape(len(pred),1),y_test.reshape(len(y_test),1)),axis=1)


array([[103015.2 , 103282.38],
       [132582.28, 144259.4 ],
       [132447.74, 146121.95],
       [ 71976.1 ,  77798.83],
       [178537.48, 191050.39],
       [116161.24, 105008.31],
       [ 67851.69,  81229.06],
       [ 98791.73,  97483.56],
       [113969.44, 110352.25],
       [167921.07, 166187.94]])

#Making a single prediction



R&D Spend = 160000
Administration = 130000
Marketing Spend = 300000
State California

Note:

$1, 0, 0, 160000, 130000, 300000 \rightarrow \textrm{scalars}$

$[1, 0, 0, 160000, 130000, 300000] \rightarrow \textrm{1D array}$

$[[1, 0, 0, 160000, 130000, 300000]] \rightarrow \textrm{2D array}$


In [25]:
lr.predict([[1,0,0,160000,130000,300000]])

array([181566.92])

In [26]:
lr.coef_

array([ 8.66e+01, -8.73e+02,  7.86e+02,  7.73e-01,  3.29e-02,  3.66e-02])

In [27]:
lr.intercept_

42467.52924853204